spring.datasource.url=jdbc:postgresql://dpg-d2h2t4er433s73ec9cl0-a:5432/eccomerce_5zt8
spring.datasource.username=eccomerce_5zt8_user
spring.datasource.password=JbxmrhF9wuukGkDQTr7LaW2PLhioNO75
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

# ---------- Swagger / API Docs ----------
springdoc.api-docs.enabled=${SPRING_DOC_API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRING_DOC_SWAGGER_UI_ENABLED:true}
springdoc.swagger-ui.path=${SPRING_DOC_SWAGGER_UI_PATH:/swagger-ui.html}

# ---------- Mail ----------
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:sawankushwaha222@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:yfhi kgnz odmk rrkw}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE:true}

# ---------- Razorpay ----------
razorpay.api.key=${RAZORPAY_KEY_ID}
razorpay.api.secret=${RAZORPAY_KEY_SECRET}

