spring.datasource.url=jdbc:mysql://avnadmin:AVNS_sRRzDBRfsz8g4G9B8mY@mysql-1ee448e4-eccomerce.c.aivencloud.com:24247/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_sRRzDBRfsz8g4G9B8mY
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

# ---------- Swagger / API Docs ----------
springdoc.api-docs.enabled=${SPRING_DOC_API_DOCS_ENABLED:true}
springdoc.swagger-ui.enabled=${SPRING_DOC_SWAGGER_UI_ENABLED:true}
springdoc.swagger-ui.path=${SPRING_DOC_SWAGGER_UI_PATH:/swagger-ui.html}

# ---------- Mail ----------
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:sawankushwaha222@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:yfhi kgnz odmk rrkw}
spring.mail.properties.mail.smtp.auth=${SPRING_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SPRING_MAIL_STARTTLS_ENABLE:true}

# ---------- Razorpay ----------
razorpay.api.key=${RAZORPAY_KEY_ID}
razorpay.api.secret=${RAZORPAY_KEY_SECRET}

